# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote-module-verification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote-module-verification.proto',
  package='org.apache.flink.statefun.e2e.remote',
  syntax='proto3',
  serialized_options=_b('\n.org.apache.flink.statefun.e2e.remote.generatedP\000'),
  serialized_pb=_b('\n remote-module-verification.proto\x12$org.apache.flink.statefun.e2e.remote\"\x08\n\x06Invoke\"\x1c\n\x0bInvokeCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"0\n\x0cInvokeResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cinvoke_count\x18\x02 \x01(\x05\x42\x32\n.org.apache.flink.statefun.e2e.remote.generatedP\x00\x62\x06proto3')
)




_INVOKE = _descriptor.Descriptor(
  name='Invoke',
  full_name='org.apache.flink.statefun.e2e.remote.Invoke',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=82,
)


_INVOKECOUNT = _descriptor.Descriptor(
  name='InvokeCount',
  full_name='org.apache.flink.statefun.e2e.remote.InvokeCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='org.apache.flink.statefun.e2e.remote.InvokeCount.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=112,
)


_INVOKERESULT = _descriptor.Descriptor(
  name='InvokeResult',
  full_name='org.apache.flink.statefun.e2e.remote.InvokeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.apache.flink.statefun.e2e.remote.InvokeResult.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invoke_count', full_name='org.apache.flink.statefun.e2e.remote.InvokeResult.invoke_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['Invoke'] = _INVOKE
DESCRIPTOR.message_types_by_name['InvokeCount'] = _INVOKECOUNT
DESCRIPTOR.message_types_by_name['InvokeResult'] = _INVOKERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Invoke = _reflection.GeneratedProtocolMessageType('Invoke', (_message.Message,), dict(
  DESCRIPTOR = _INVOKE,
  __module__ = 'remote_module_verification_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.flink.statefun.e2e.remote.Invoke)
  ))
_sym_db.RegisterMessage(Invoke)

InvokeCount = _reflection.GeneratedProtocolMessageType('InvokeCount', (_message.Message,), dict(
  DESCRIPTOR = _INVOKECOUNT,
  __module__ = 'remote_module_verification_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.flink.statefun.e2e.remote.InvokeCount)
  ))
_sym_db.RegisterMessage(InvokeCount)

InvokeResult = _reflection.GeneratedProtocolMessageType('InvokeResult', (_message.Message,), dict(
  DESCRIPTOR = _INVOKERESULT,
  __module__ = 'remote_module_verification_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.flink.statefun.e2e.remote.InvokeResult)
  ))
_sym_db.RegisterMessage(InvokeResult)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
