//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: kafka-egress.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KafkaProducerRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueBytes []byte `protobuf:"bytes,2,opt,name=value_bytes,json=valueBytes,proto3" json:"value_bytes,omitempty"`
	Topic      string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *KafkaProducerRecord) Reset() {
	*x = KafkaProducerRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafka_egress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KafkaProducerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaProducerRecord) ProtoMessage() {}

func (x *KafkaProducerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_egress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaProducerRecord.ProtoReflect.Descriptor instead.
func (*KafkaProducerRecord) Descriptor() ([]byte, []int) {
	return file_kafka_egress_proto_rawDescGZIP(), []int{0}
}

func (x *KafkaProducerRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KafkaProducerRecord) GetValueBytes() []byte {
	if x != nil {
		return x.ValueBytes
	}
	return nil
}

func (x *KafkaProducerRecord) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

var File_kafka_egress_proto protoreflect.FileDescriptor

var file_kafka_egress_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2d, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x69, 0x6f, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x66, 0x75,
	0x6e, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5e, 0x0a, 0x13,
	0x4b, 0x61, 0x66, 0x6b, 0x61, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x42, 0x3e, 0x0a, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b,
	0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x66, 0x75, 0x6e, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x65, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x50, 0x01,
	0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kafka_egress_proto_rawDescOnce sync.Once
	file_kafka_egress_proto_rawDescData = file_kafka_egress_proto_rawDesc
)

func file_kafka_egress_proto_rawDescGZIP() []byte {
	file_kafka_egress_proto_rawDescOnce.Do(func() {
		file_kafka_egress_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafka_egress_proto_rawDescData)
	})
	return file_kafka_egress_proto_rawDescData
}

var file_kafka_egress_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kafka_egress_proto_goTypes = []interface{}{
	(*KafkaProducerRecord)(nil), // 0: io.statefun.sdk.egress.KafkaProducerRecord
}
var file_kafka_egress_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kafka_egress_proto_init() }
func file_kafka_egress_proto_init() {
	if File_kafka_egress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafka_egress_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KafkaProducerRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafka_egress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_egress_proto_goTypes,
		DependencyIndexes: file_kafka_egress_proto_depIdxs,
		MessageInfos:      file_kafka_egress_proto_msgTypes,
	}.Build()
	File_kafka_egress_proto = out.File
	file_kafka_egress_proto_rawDesc = nil
	file_kafka_egress_proto_goTypes = nil
	file_kafka_egress_proto_depIdxs = nil
}
