version: "3.8"
services:
  flink-statefun:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        tag: 11
    volumes:
      - ..:/src:cached
      - /var/run/docker.sock:/var/run/docker.sock
    user: vscode
    # Ensure the container runs forever
    command: "-f /dev/null"
    entrypoint: /usr/bin/tail
    tty: true
    expose:
      - "9090"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
