
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import re


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# https://github.com/djungelorm/sphinx-tabs
extensions = ['sphinx.ext.ifconfig', 'sphinx_tabs.tabs']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# Warn about broken references
nitpicky = True

# General information about the project.
project = u'Stateful Functions'
copyright = u'2019, The Apache Software Foundation.'
author = u'The Apache Flink authors.'

# Render it manually in the footer.html
html_show_copyright = False

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'2.1-SNAPSHOT'
# The full version, including alpha/beta/rc tags.
release = u'2.1.0'
# The latest Flink version supported by Stateful Functions
flinkVersion = u'1.10'
# The latest full Flink version supported by Stateful Functions
flinkRelease = u'1.10.0'
# The source code repository
repo = "https://github.com/apache/flink-statefun"

# The examples directory
example_source = repo + "/tree/master/statefun-examples"

# hide source link
html_show_sourcelink = False
# required for the search to work
html_copy_source = True

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', "hidden"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'titles_only': True,
    'canonical_url': 'https://statefun.io/',
    'display_version': False,
    #'prev_next_buttons_location': None
}

html_show_sphinx = False


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'StatefulFunctionsdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'StatefulFunctions.tex', u'Stateful Functions Documentation',
     u'Apache Flink', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'stateful-functions', u'Stateful Functions Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Stateful Functions', u'Stateful Functions Documentation',
     author, 'Stateful Functions', 'One line description of project.',
     'Miscellaneous'),
]

# -- Settings for sphinxcontrib-versioning --------------------------------
scv_greatest_tag = True
scv_show_banner = True
scv_banner_greatest_tag = True
scv_sort = ('semver', 'alpha')
scv_whitelist_branches = (re.compile(r'^v\d+\.\d+$'),
                          re.compile(r'^v\d+\.\d+\.\d+$'),
                          'latest')
scv_whitelist_tags = (re.compile(r'^v\d+\.\d+$'),
                      re.compile(r'^v\d+\.\d+\.\d+$'),
                      'latest')

## Sphynx macros do not work inside of
## code blocks, so we include these custom
## replacements to autofill in versions in
## all places.
def customReplace(app, docname, source):
    result = source[0]
    for key in app.config.custom_replacements:
        result = result.replace(key, app.config.custom_replacements[key])
    source[0] = result

custom_replacements = {
    "{release}"      : release,
    "{version}"      : version,
    "{flink}"        : u'Apache Flink®',
    "{flinkVersion}" : flinkVersion,
    "{flinkRelease}" : flinkRelease,
    "{repo}"         : repo,
    "{examples}"     : example_source
}

def setup(app):
   app.add_config_value('custom_replacements', {}, True)
   app.connect('source-read', customReplace)
