# -*- coding: utf-8 -*-
################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='k8s.demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0emessages.proto\x12\x08k8s.demo\"\x1f\n\nLoginEvent\x12\x11\n\tuser_name\x18\x01 \x01(\t\"\x19\n\tSeenCount\x12\x0c\n\x04seen\x18\x01 \x01(\x03\x62\x06proto3'
)




_LOGINEVENT = _descriptor.Descriptor(
  name='LoginEvent',
  full_name='k8s.demo.LoginEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='k8s.demo.LoginEvent.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_SEENCOUNT = _descriptor.Descriptor(
  name='SeenCount',
  full_name='k8s.demo.SeenCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seen', full_name='k8s.demo.SeenCount.seen', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['LoginEvent'] = _LOGINEVENT
DESCRIPTOR.message_types_by_name['SeenCount'] = _SEENCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginEvent = _reflection.GeneratedProtocolMessageType('LoginEvent', (_message.Message,), {
  'DESCRIPTOR' : _LOGINEVENT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:k8s.demo.LoginEvent)
  })
_sym_db.RegisterMessage(LoginEvent)

SeenCount = _reflection.GeneratedProtocolMessageType('SeenCount', (_message.Message,), {
  'DESCRIPTOR' : _SEENCOUNT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:k8s.demo.SeenCount)
  })
_sym_db.RegisterMessage(SeenCount)


# @@protoc_insertion_point(module_scope)
